import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider"
import DynamicIsland from "../app/dynamic-island" // <-- Added import
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Note: Ensure RootLayoutProps is defined or change to { children }: { children: React.ReactNode }
export default function RootLayout({ children }: any) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {/* The Island sits here globally, floating above everything */}
            <DynamicIsland /> 
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}